version: "3"

vars:
  FRONTEND_DIR: frontend
  BACKEND_PROJECT: backend/MiLyst.Api
  TASK_DIR: .task

  BACKEND_URLS: http://127.0.0.1:5145

  POSTGRES_CONTAINER: milyst-postgres
  POSTGRES_PORT: "5432"
  POSTGRES_USER: milyst
  POSTGRES_PASSWORD: milyst
  POSTGRES_DB: milyst_dev

  FRONTEND_PID: .task/frontend.pid
  BACKEND_PID: .task/backend.pid

  FRONTEND_LOG: .task/frontend.log
  BACKEND_LOG: .task/backend.log

tasks:
  default:
    cmds:
      - task -l
    silent: true

  init:
    cmds:
      - mkdir -p {{.TASK_DIR}}
    status:
      - test -d {{.TASK_DIR}}

  deps:
    deps:
      - deps:root
      - deps:frontend
      - deps:backend

  deps:root:
    cmds:
      - npm ci

  deps:frontend:
    cmds:
      - npm --prefix {{.FRONTEND_DIR}} ci

  deps:backend:
    cmds:
      - dotnet restore {{.BACKEND_PROJECT}}

  build:
    deps:
      - build:backend
      - build:frontend

  build:frontend:
    cmds:
      - npm --prefix {{.FRONTEND_DIR}} run build

  build:backend:
    cmds:
      - dotnet build {{.BACKEND_PROJECT}} -c Release

  test:
    deps:
      - test:backend
      - test:frontend

  test:backend:
    cmds:
      - |
        TEST_PROJECTS=$(find backend \( -name '*Test*.csproj' -o -name '*Tests*.csproj' \) -print 2>/dev/null || true)
        if [ -z "$TEST_PROJECTS" ]; then
          echo "No backend test projects found; skipping."
          exit 0
        fi
        if [ "${RUN_INTEGRATION_TESTS:-0}" != "1" ]; then
          TEST_PROJECTS=$(echo "$TEST_PROJECTS" | grep -v 'IntegrationTests' || true)
        fi
        echo "$TEST_PROJECTS" | while read -r proj; do
          if [ -n "$proj" ]; then
            echo "Running tests: $proj"
            dotnet test "$proj" -c Release
          fi
        done

  test:integration:
    desc: Run backend integration tests (requires Docker)
    cmds:
      - |
        if ! command -v docker >/dev/null 2>&1; then
          echo "Docker is required for integration tests but was not found on PATH."
          exit 1
        fi
        if ! docker info >/dev/null 2>&1; then
          echo "Docker is required for integration tests but does not appear to be running (docker info failed)."
          exit 1
        fi
        # Clear proxy environment variables because they can interfere with Testcontainers/Docker communication.
        env \
          -u HTTP_PROXY -u http_proxy \
          -u HTTPS_PROXY -u https_proxy \
          -u ALL_PROXY -u all_proxy \
          RUN_INTEGRATION_TESTS=1 \
          task test:backend

  test:frontend:
    cmds:
      - echo "No frontend tests configured; skipping."

  dev:
    desc: Run backend in the foreground (it starts Vite automatically in Development)
    deps:
      - postgres:start
    cmds:
      - ASPNETCORE_URLS={{.BACKEND_URLS}} dotnet run --project {{.BACKEND_PROJECT}}

  postgres:start:
    desc: Start local Postgres in Docker for development
    cmds:
      - |
        if ! command -v docker >/dev/null 2>&1; then
          echo "Docker is required for postgres:start but was not found on PATH."
          exit 1
        fi

        wait_for_postgres() {
          local timeout_seconds=20
          local start_ts
          start_ts=$(date +%s)

          while true; do
            if docker exec {{.POSTGRES_CONTAINER}} pg_isready -U {{.POSTGRES_USER}} -d {{.POSTGRES_DB}} >/dev/null 2>&1; then
              break
            fi

            if [ $(( $(date +%s) - start_ts )) -ge $timeout_seconds ]; then
              echo "Timed out waiting for Postgres to become ready."
              exit 1
            fi

            sleep 0.5
          done
        }

        if docker ps -a --format '{{"{{.Names}}"}}' | grep -q '^{{.POSTGRES_CONTAINER}}$'; then
          docker start {{.POSTGRES_CONTAINER}} >/dev/null 2>&1 || true
          wait_for_postgres
          echo "Postgres container already exists; ready: {{.POSTGRES_CONTAINER}}."
          exit 0
        fi

        docker run -d \
          --name {{.POSTGRES_CONTAINER}} \
          -e POSTGRES_USER={{.POSTGRES_USER}} \
          -e POSTGRES_PASSWORD={{.POSTGRES_PASSWORD}} \
          -e POSTGRES_DB={{.POSTGRES_DB}} \
          -p {{.POSTGRES_PORT}}:5432 \
          postgres:16-alpine >/dev/null

        wait_for_postgres

        echo "Postgres started: localhost:{{.POSTGRES_PORT}} (db={{.POSTGRES_DB}} user={{.POSTGRES_USER}})"

  postgres:stop:
    desc: Stop local Postgres container
    cmds:
      - |
        if docker ps -a --format '{{"{{.Names}}"}}' | grep -q '^{{.POSTGRES_CONTAINER}}$'; then
          docker stop {{.POSTGRES_CONTAINER}} >/dev/null || true
          echo "Postgres stopped."
        else
          echo "Postgres container not found; nothing to stop."
        fi

  postgres:rm:
    desc: Remove local Postgres container (data will be lost)
    cmds:
      - |
        if docker ps -a --format '{{"{{.Names}}"}}' | grep -q '^{{.POSTGRES_CONTAINER}}$'; then
          docker rm -f {{.POSTGRES_CONTAINER}} >/dev/null || true
          echo "Postgres container removed."
        else
          echo "Postgres container not found; nothing to remove."
        fi

  postgres:status:
    desc: Show Postgres container status
    cmds:
      - |
        if docker ps --format '{{"{{.Names}}"}}' | grep -q '^{{.POSTGRES_CONTAINER}}$'; then
          echo "Postgres: running ({{.POSTGRES_CONTAINER}})"
        else
          echo "Postgres: stopped"
        fi

  db:migrate:
    desc: Apply EF Core migrations to the configured dev database
    cmds:
      - dotnet ef database update --project backend/MiLyst.Infrastructure --startup-project backend/MiLyst.Api

  dev:frontend:
    cmds:
      - npm --prefix {{.FRONTEND_DIR}} run dev -- --host

  dev:backend:
    deps:
      - postgres:start
    cmds:
      - ASPNETCORE_URLS={{.BACKEND_URLS}} dotnet run --project {{.BACKEND_PROJECT}}

  start:
    deps:
      - start:backend

  start:backend:
    deps:
      - init
    cmds:
      - |
        if [ -f {{.BACKEND_PID}} ] && kill -0 "$(cat {{.BACKEND_PID}})" 2>/dev/null; then
          echo "Backend already running (pid $(cat {{.BACKEND_PID}}))."
          exit 0
        fi
        rm -f {{.BACKEND_PID}}
        export ASPNETCORE_URLS={{.BACKEND_URLS}}
        nohup dotnet run --project {{.BACKEND_PROJECT}} > {{.BACKEND_LOG}} 2>&1 &
        echo $! > {{.BACKEND_PID}}
        echo "Backend started (pid $(cat {{.BACKEND_PID}})). Logs: {{.BACKEND_LOG}}"

  start:frontend:
    deps:
      - init
    cmds:
      - |
        if [ -f {{.FRONTEND_PID}} ] && kill -0 "$(cat {{.FRONTEND_PID}})" 2>/dev/null; then
          echo "Frontend already running (pid $(cat {{.FRONTEND_PID}}))."
          exit 0
        fi
        rm -f {{.FRONTEND_PID}}
        nohup npm --prefix {{.FRONTEND_DIR}} run dev -- --host > {{.FRONTEND_LOG}} 2>&1 &
        echo $! > {{.FRONTEND_PID}}
        echo "Frontend started (pid $(cat {{.FRONTEND_PID}})). Logs: {{.FRONTEND_LOG}}"

  stop:
    deps:
      - stop:frontend
      - stop:backend

  stop:backend:
    deps:
      - init
    cmds:
      - |
        if [ ! -f {{.BACKEND_PID}} ]; then
          echo "Backend PID file not found; nothing to stop."
          exit 0
        fi
        PID=$(cat {{.BACKEND_PID}})
        if ! kill -0 "$PID" 2>/dev/null; then
          rm -f {{.BACKEND_PID}}
          echo "Backend not running; cleaned stale PID file."
          exit 0
        fi
        CHILDREN=$(pgrep -P "$PID" 2>/dev/null || true)
        if [ -n "$CHILDREN" ]; then
          kill $CHILDREN 2>/dev/null || true
        fi
        kill "$PID" 2>/dev/null || true
        sleep 1
        if kill -0 "$PID" 2>/dev/null; then
          CHILDREN=$(pgrep -P "$PID" 2>/dev/null || true)
          if [ -n "$CHILDREN" ]; then
            kill -9 $CHILDREN 2>/dev/null || true
          fi
          kill -9 "$PID" 2>/dev/null || true
        fi
        rm -f {{.BACKEND_PID}}
        echo "Backend stopped."

  stop:frontend:
    deps:
      - init
    cmds:
      - |
        if [ ! -f {{.FRONTEND_PID}} ]; then
          echo "Frontend PID file not found; nothing to stop."
          exit 0
        fi
        PID=$(cat {{.FRONTEND_PID}})
        if ! kill -0 "$PID" 2>/dev/null; then
          rm -f {{.FRONTEND_PID}}
          echo "Frontend not running; cleaned stale PID file."
          exit 0
        fi
        CHILDREN=$(pgrep -P "$PID" 2>/dev/null || true)
        if [ -n "$CHILDREN" ]; then
          kill $CHILDREN 2>/dev/null || true
        fi
        kill "$PID" 2>/dev/null || true
        sleep 1
        if kill -0 "$PID" 2>/dev/null; then
          CHILDREN=$(pgrep -P "$PID" 2>/dev/null || true)
          if [ -n "$CHILDREN" ]; then
            kill -9 $CHILDREN 2>/dev/null || true
          fi
          kill -9 "$PID" 2>/dev/null || true
        fi
        rm -f {{.FRONTEND_PID}}
        echo "Frontend stopped."

  status:
    deps:
      - status:backend
      - status:frontend

  status:backend:
    deps:
      - init
    cmds:
      - |
        if [ -f {{.BACKEND_PID}} ] && kill -0 "$(cat {{.BACKEND_PID}})" 2>/dev/null; then
          echo "Backend: running (pid $(cat {{.BACKEND_PID}}))"
        else
          echo "Backend: stopped"
        fi

  status:frontend:
    deps:
      - init
    cmds:
      - |
        if [ -f {{.FRONTEND_PID}} ] && kill -0 "$(cat {{.FRONTEND_PID}})" 2>/dev/null; then
          echo "Frontend: running (pid $(cat {{.FRONTEND_PID}}))"
        else
          echo "Frontend: stopped"
        fi

  clean:
    cmds:
      - rm -rf {{.TASK_DIR}}
      - rm -rf frontend/dist
      - find backend -type d \( -name bin -o -name obj \) -prune -exec rm -rf {} +
